server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: provider-Gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
          - Path=/api/**
#        - id: path_route
#          uri: http://localhost:8123
#          predicates:
#          - Path=/api/**
#          filters:
#          - AddRequestHeader=qinjiu, hahahhaa
#          - AddRequestParameter=name, tuozi
#          - name: CircuitBreaker
#            args:
#              name: myCircuitBreaker
#              fallbackUri: forward:/fallback
#
#        - id: fallback
#          uri: http://localhost/
#          predicates:
#            - Path=/fallback
#
#
#        - id: path_route2
#          uri: https://baidu.com
#          predicates:
#          - Path=/baidu


#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: trace



dubbo:
  application:
    name: nacos-consumer

  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

